import { pageMetadata } from '@/lib/seo';
import { ArrowLeft, ArrowUpRight, Play } from 'lucide-react';
import { films, type Film } from '@/lib/portfolio';
export const metadata = pageMetadata('/studio', 'Studio — Films, Selfies & Experiments', 'H3 action shorts, George and Dwight on AI, UGC, song films, and a collection of video art by Seth Pratt.');
function FilmCards({items,featured=false}:{items:Film[];featured?:boolean}){return <div className={'studio-film-grid'+(featured?' studio-featured-grid':'')}>{items.map(art=><a href={'/studio/'+art.slug} className="art-card" key={art.slug}><div className="art-poster"><img src={'/studio/'+art.poster+'.jpg'} alt={art.title+' — still frame'} width={art.width} height={art.height} loading="lazy"/><span className="art-open"><Play size={16} aria-hidden="true"/>Watch</span></div><div className="art-card-info"><div><h3>{art.title}</h3><p>{art.subtitle}</p></div><span>{art.duration}</span></div></a>)}</div>}
export default function Studio(){return <main id="main" className="studio-page"><header className="wrap studio-heading"><a href="/" className="back-link"><ArrowLeft size={16} aria-hidden="true"/>Back to the professional side</a><div className="studio-heading-row"><div><p className="eyebrow">The independent practice</p><h1>The <span className="serif">Studio.</span></h1></div><p>Short films, familiar faces,<br/>and the experiments behind them.</p></div><nav className="studio-sections" aria-label="Studio collections"><a href="#featured">Featured renders <span>04</span></a><a href="#films">Films & music <span>03</span></a><a href="#video-art">Selfies & early art <span>05</span></a><a href="#experiments">Early experiments <span>02</span></a></nav></header>
<section id="featured" className="wrap studio-collection"><div className="collection-title"><div><p className="eyebrow">MiniMax H3 / 2026</p><h2>Familiar faces. New worlds.</h2></div><span>Action, comedy & UGC</span></div><FilmCards featured items={films.filter(f=>f.collection==='featured')}/></section>
<section id="films" className="studio-film-band"><div className="wrap studio-collection"><div className="collection-title"><div><p className="eyebrow">Stories & songs / 2026</p><h2>A little further into the imagination.</h2></div><span>Original AI-assisted productions</span></div><FilmCards items={films.filter(f=>f.collection==='films')}/></div></section>
<section id="video-art" className="wrap studio-collection"><div className="collection-title"><div><p className="eyebrow">From the first collection / 2025</p><h2>Selfies & early art.</h2></div><span>Portraits, landscapes & motion studies</span></div><FilmCards items={[...films.filter(f=>f.collection==='archive')].sort((a,b)=>Number(['ego','reflections-in-motion'].includes(b.slug))-Number(['ego','reflections-in-motion'].includes(a.slug)))}/></section>
<section id="experiments" className="experiments-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">From the archive</p><h2>Early experiments.</h2></div><p>First explorations in browser-based graphics. Kept as a record of the process, not a showcase of current simulation work.</p></div><div className="experiment-grid">{[{title:'Fractal Tunnel',image:'fractal',slug:'fractal-tunnel',description:'An early WebGL study in procedural patterns and movement through a fractal space.'},{title:'Solar System',image:'solar',slug:'solar-system',description:'An early Three.js visualization exploring orbital motion and interactive 3D scenes.'}].map(item=><article className="experiment-card" id={item.slug} key={item.slug}><img src={'/studio/'+item.image+'.jpg'} alt={item.title+' — archived preview'} width="200" height="160" loading="lazy"/><div><span className="archive-label">Archived · 2025</span><h3>{item.title}</h3><p>{item.description}</p><a className="text-link" href={'https://github.com/sipratt-p/portfolio/blob/main/app/simulations/'+item.slug+'/page.tsx'} target="_blank" rel="noreferrer">View original source <ArrowUpRight size={15} aria-hidden="true"/><span className="sr-only"> (opens in a new tab)</span></a></div></article>)}</div></div></section></main>}
