// Editorial summaries from Seth's existing portfolio; no unverified impact metrics.
export const projects = [
  {slug:'enterprise-ai',company:'NVIDIA',category:'Enterprise AI',title:'Making enterprise AI accessible',name:'Enterprise GenAI Platform',image:'nvidiangc',summary:'Product experience for the NGC Catalog and analytics for the API Catalog.',role:'UI/UX lead, NGC Catalog · Analytics lead, API Catalog',audience:'Enterprise AI teams and developers',context:'Enterprise developers need a clear path from discovering AI models to using them within their own infrastructure. My work spanned the NGC Catalog experience and analytics for the API Catalog.',contribution:'I led UI/UX for the NGC Catalog, supporting distribution of NVIDIA’s on-premises generative AI ecosystem. I also led analytics for the API Catalog, which gives developers API access to LLMs and agentic blueprints.',focus:['Model and platform discovery','Developer experience','Product analytics','On-premises AI and APIs'],imageAlt:'NVIDIA NGC Catalog interface showing catalog navigation and featured resources'},
  {slug:'universal-search',company:'Lyft',category:'Developer productivity',title:'One place to find what matters',name:'Universal Search Infrastructure',image:'lyftproject',summary:'Universal search across company knowledge, people, and internal tools.',role:'Product owner · Senior Product Manager',audience:'Employees and internal engineering teams',context:'Information inside a company lives across many systems. The universal search initiative brought company-wide information into a unified discovery experience at Lyft.',contribution:'I owned the internal universal search product, built on Google Cloud Search and Elasticsearch. My broader developer-productivity portfolio included Lyft Home, team org charts, short links, and people profiles.',focus:['Unified information discovery','People search and filters','Internal developer tools','Google Cloud Search and Elasticsearch'],imageAlt:'Lyft internal product interface from the universal search portfolio'},
  {slug:'av-validation',company:'NVIDIA',category:'Autonomous systems',title:'Confidence before the road',name:'AV Test Management & Traceability',image:'kebana',summary:'Test management and requirements traceability for autonomous vehicle features.',role:'Product lead',audience:'Autonomous vehicle engineering and validation teams',context:'Autonomous vehicle features must be evaluated against system-level and vehicle-level requirements before deployment. That calls for a clear connection between requirements, test cases, and test results.',contribution:'I led product for the autonomous vehicle test management platform and traceability tooling, supporting how new features are tested before being put on the road.',focus:['Test management','Requirements traceability','Feature validation workflows','Engineering visibility'],imageAlt:'Test management and analytics interface from the autonomous vehicle platform'},
  {slug:'reconcile',company:'Intuit',category:'Financial software',title:'A clearer path through reconciliation',name:'Reconcile Redesign',image:'nav',summary:'A redesign of the transaction reconciliation experience for small businesses.',role:'Product Manager',audience:'Small business owners',context:'Transaction reconciliation is an essential part of managing small business finances. This project focused on making that workflow easier to understand and use.',contribution:'I drove the redesign of Reconcile with a focus on user experience and efficiency. It sat within a broader Intuit portfolio covering enterprise search, desktop applications, navigation, and platform performance.',focus:['Financial workflows','User experience','Navigation','Small business software'],imageAlt:'Intuit product screenshot from the Reconcile redesign portfolio'},
  {slug:'experimentation',company:'Intuit',category:'Data platforms',title:'Better tools for learning what works',name:'Analytics & Experimentation Platform',image:'wasabi',summary:'Internal experimentation and analytics tooling for product teams.',role:'Internal Product Manager',audience:'Product, analytics, and engineering teams',context:'Experimentation platforms give product teams a shared foundation for testing changes and learning from results. My work combined internal platform ownership with improvements to customer-facing product experiences.',contribution:'I managed the Intuit Experimentation Platform and drove the creation of experimentation and analytics tooling, alongside features for search, navigation, and platform performance.',focus:['Experimentation infrastructure','Product analytics','A/B testing','Platform adoption'],imageAlt:'Wasabi experimentation platform interface from the Intuit project'},
] as const;

export const career = [
  {company:'NVIDIA',role:'AI Product Leader',years:'2022 — Present',detail:'AI Research, enterprise AI, developer platforms, and autonomous vehicle validation.'},
  {company:'Lyft',role:'Senior Product Manager',years:'2019 — 2022',detail:'Level 5 Autonomous Vehicles · Universal search, developer productivity, and data infrastructure.'},
  {company:'Intuit',role:'Product Manager',years:'2017 — 2019',detail:'Search, small business finance, and experimentation platforms.'},
  {company:'Meta',role:'Product Management',years:'2015 — 2017',detail:'Formerly Facebook. Consumer growth, experimentation, and analytics tooling.'},
  {company:'Visa',role:'Associate Product Manager',years:'2014 — 2015',detail:'Payment gateways and enterprise product delivery.'},
  {company:'Amgen',role:'Project Manager',years:'2013 — 2014',detail:'Research operations and medical database resource planning.'},
] as const;

export const artworks = [
  {slug:'headlands-journey',title:'Headlands Journey',subtitle:'Shifting landscapes',description:'Coastal landscapes dissolve into a shifting visual journey through the Marin Headlands.',poster:'headlands',video:'marin',duration:'20 sec',width:1616,height:2160},
  {slug:'abstract-flow',title:'Abstract Flow',subtitle:'Patterns in motion',description:'An abstract study of fluid patterns, color, and movement.',poster:'abstract',video:'background',duration:'15 sec',width:1280,height:854},
  {slug:'ego',title:'Ego',subtitle:'Digital consciousness',description:'A moving portrait exploring identity and digital transformation.',poster:'ego',video:'ego',duration:'20 sec',width:1248,height:1664},
  {slug:'impressionist-dream',title:'Impressionist Dream',subtitle:'A painterly interlude',description:'A short exploration of shifting color and impressionistic imagery.',poster:'impressionist',video:'impressionistdream',duration:'20 sec',width:1776,height:1184},
  {slug:'reflections-in-motion',title:'Reflections in Motion',subtitle:'A changing self-portrait',description:'An experimental self-portrait, reimagined through motion and visual transformation.',poster:'reflections',video:'selfie',duration:'20 sec',width:1248,height:1664},
] as const;

export type Film={slug:string;title:string;subtitle:string;description:string;poster:string;video:string;duration:string;width:number;height:number;year:string;audio:boolean;collection:'featured'|'films'|'archive';kind:string;note?:string;captions?:string;transcript?:string};
export const films:Film[]=[
 {slug:'bridge-fight',title:'Spider-Man vs. Goblin',subtitle:'Robin vs. Seth · Final cut',description:'Robin as Spider-Man. Seth as the Green Goblin. A multi-shot action short on the Golden Gate Bridge, built with MiniMax H3.',poster:'bridge-fight',video:'bridge-fight',duration:'1:38',width:720,height:1234,year:'2026',audio:true,collection:'featured',kind:'AI-generated fan film',note:'Final V7 cut, from the 2× upscale master. A personal fan-film experiment; not affiliated with Marvel or Sony.'},
 {slug:'matrix-bullet-time',title:'The Matrix: Bullet Time',subtitle:'Seth vs. Agent Smith · Final sequence',description:'A bullet-time dodge becomes a rooftop fight. A short study in likeness, action choreography, and shot-to-shot continuity with MiniMax H3.',poster:'matrix-bullet-time',video:'matrix-bullet-time',duration:'0:27',width:960,height:544,year:'2026',audio:true,collection:'featured',kind:'AI-generated fan film',note:'Final scored sequence, with the removed-line edit. A personal fan-film experiment; not affiliated with The Matrix franchise.'},
 {slug:'h3-ugc',captions:'/captions/h3-ugc.vtt',title:'UGC, made with H3',subtitle:'Sophia · Expert-style concept',description:'An AI-generated presenter in a short, conversational UGC concept for the Dr. Grey creative pipeline. Picture, voice, and lip movement were generated together with MiniMax H3.',poster:'h3-ugc',video:'h3-ugc',duration:'0:14',width:544,height:960,year:'2026',audio:true,collection:'featured',kind:'AI-generated UGC concept',note:'An AI-generated presenter, not a real customer testimonial. This portfolio presents a production example, not medical advice.'},
 {slug:'george-dwight-ai',title:'George & Dwight on AI',subtitle:'Seinfeld meets The Office',description:'George Costanza and Dwight Schrute argue about AI, jobs, and efficiency across a diner table. A three-scene comedy experiment rendered with MiniMax H3.',poster:'george-dwight-ai',video:'george-dwight-ai',duration:'0:41',width:960,height:544,year:'2026',audio:true,collection:'featured',kind:'AI-generated comedy',note:'Final three-scene cut. An AI-generated fan parody featuring fictional characters from Seinfeld and The Office, not an original episode or a performance by the actors.'},
 {slug:'fable',title:'Fable',subtitle:'An AI-assisted song film',description:'A music film about memory, continuity, and being seen. Original AI-authored lyrics and an ACE-Step vocal performance meet a beat-cut sequence of H3 imagery.',poster:'fable',video:'fable',duration:'3:20',width:960,height:544,year:'2026',audio:true,collection:'films',kind:'AI-assisted music film'},
 {slug:'the-keeper',title:'The Keeper',subtitle:'A lighthouse, a ledger, a life',description:'A lighthouse keeper writes down what the fog takes away. A narrative experiment in character and voice consistency across independently generated H3 scenes.',poster:'the-keeper',video:'the-keeper',duration:'4:41',width:960,height:544,year:'2026',audio:true,collection:'films',kind:'AI-assisted narrative short'},
 {slug:'second-winter',title:'Second Winter',subtitle:'A composed song, an imagined world',description:'An original AI-authored melody and lyrics, performed with SoulX-Singer and paired with an H3-generated film. An exploration of music and visual storytelling in one piece.',poster:'second-winter',video:'second-winter',duration:'2:35',width:960,height:544,year:'2026',audio:true,collection:'films',kind:'AI-assisted music film'},
 ...artworks.map(a=>({...a,year:'2025',audio:false,collection:'archive' as const,kind:'Digital video study'})),
];
